version: "3.11.8"

services:
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    environment:
       - DB_URL=postgresql://postgres:123@flask_db:5432/Demo
    networks:
      - fastapi-app

networks: 
  fastapi-app:
    name: fastapi-app
    external: true