version: "3.11.8"

services:
  flask_db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
    ports:
      - "5436:5432"
    networks:
      - fastapi-app
    
networks: 
  fastapi-app:
    name: fastapi-app
    #external: true
    driver: bridge 